services:
  paradedb:
    image: paradedb/paradedb:latest
    environment:
      POSTGRES_USER: cafi
      POSTGRES_PASSWORD: cafi
      POSTGRES_DB: cafi
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cafi -d cafi"]
      interval: 5s
      timeout: 5s
      retries: 5

#  cafi-server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      DATABASE_URL: "postgres://cafi:cafi@paradedb:5432/cafi"
#    depends_on:
#      paradedb:
#        condition: service_healthy
#    ports:
#      - "50051:50051"

volumes:
  pgdata:
