// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cafi/v1/cafi.proto

package cafiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType describes whether a file event is an upsert or a deletion.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_UPSERT      EventType = 1
	EventType_EVENT_TYPE_DELETED     EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_UPSERT",
		2: "EVENT_TYPE_DELETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_UPSERT":      1,
		"EVENT_TYPE_DELETED":     2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cafi_v1_cafi_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_cafi_v1_cafi_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{0}
}

// Handshake is the first message the client sends after opening a Sync stream.
type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	SourceCode    string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Handshake) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

// FileEvent describes a filesystem change on the client side.
type FileEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blake3        string                 `protobuf:"bytes,1,opt,name=blake3,proto3" json:"blake3,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mtime         int64                  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	EventType     EventType              `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=cafi.v1.EventType" json:"event_type,omitempty"`
	SourceCode    string                 `protobuf:"bytes,7,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{1}
}

func (x *FileEvent) GetBlake3() string {
	if x != nil {
		return x.Blake3
	}
	return ""
}

func (x *FileEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEvent) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FileEvent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEvent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *FileEvent) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

// ClientMessage is the envelope sent by the client on the Sync stream.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Handshake
	//	*ClientMessage_FileEvent
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *ClientMessage) GetFileEvent() *FileEvent {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_FileEvent); ok {
			return x.FileEvent
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type ClientMessage_FileEvent struct {
	FileEvent *FileEvent `protobuf:"bytes,2,opt,name=file_event,json=fileEvent,proto3,oneof"`
}

func (*ClientMessage_Handshake) isClientMessage_Message() {}

func (*ClientMessage_FileEvent) isClientMessage_Message() {}

// EventAck confirms that an event was persisted on the server.
type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blake3        string                 `protobuf:"bytes,1,opt,name=blake3,proto3" json:"blake3,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{3}
}

func (x *EventAck) GetBlake3() string {
	if x != nil {
		return x.Blake3
	}
	return ""
}

func (x *EventAck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// PullRequest is reserved for v1 and is never emitted in v0.
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{4}
}

// SyncError reports an error to the client.
type SyncError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Fatal         bool                   `protobuf:"varint,2,opt,name=fatal,proto3" json:"fatal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncError) Reset() {
	*x = SyncError{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncError) ProtoMessage() {}

func (x *SyncError) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncError.ProtoReflect.Descriptor instead.
func (*SyncError) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{5}
}

func (x *SyncError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncError) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

// ServerMessage is the envelope sent by the server on the Sync stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_EventAck
	//	*ServerMessage_PullRequest
	//	*ServerMessage_SyncError
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_cafi_v1_cafi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cafi_v1_cafi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_cafi_v1_cafi_proto_rawDescGZIP(), []int{6}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetEventAck() *EventAck {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_EventAck); ok {
			return x.EventAck
		}
	}
	return nil
}

func (x *ServerMessage) GetPullRequest() *PullRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_PullRequest); ok {
			return x.PullRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetSyncError() *SyncError {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_SyncError); ok {
			return x.SyncError
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_EventAck struct {
	EventAck *EventAck `protobuf:"bytes,1,opt,name=event_ack,json=eventAck,proto3,oneof"`
}

type ServerMessage_PullRequest struct {
	PullRequest *PullRequest `protobuf:"bytes,2,opt,name=pull_request,json=pullRequest,proto3,oneof"`
}

type ServerMessage_SyncError struct {
	SyncError *SyncError `protobuf:"bytes,3,opt,name=sync_error,json=syncError,proto3,oneof"`
}

func (*ServerMessage_EventAck) isServerMessage_Message() {}

func (*ServerMessage_PullRequest) isServerMessage_Message() {}

func (*ServerMessage_SyncError) isServerMessage_Message() {}

var File_cafi_v1_cafi_proto protoreflect.FileDescriptor

const file_cafi_v1_cafi_proto_rawDesc = "" +
	"\n" +
	"\x12cafi/v1/cafi.proto\x12\acafi.v1\"S\n" +
	"\tHandshake\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\"\xd2\x01\n" +
	"\tFileEvent\x12\x16\n" +
	"\x06blake3\x18\x01 \x01(\tR\x06blake3\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x121\n" +
	"\n" +
	"event_type\x18\x06 \x01(\x0e2\x12.cafi.v1.EventTypeR\teventType\x12\x1f\n" +
	"\vsource_code\x18\a \x01(\tR\n" +
	"sourceCode\"\x83\x01\n" +
	"\rClientMessage\x122\n" +
	"\thandshake\x18\x01 \x01(\v2\x12.cafi.v1.HandshakeH\x00R\thandshake\x123\n" +
	"\n" +
	"file_event\x18\x02 \x01(\v2\x12.cafi.v1.FileEventH\x00R\tfileEventB\t\n" +
	"\amessage\"6\n" +
	"\bEventAck\x12\x16\n" +
	"\x06blake3\x18\x01 \x01(\tR\x06blake3\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\r\n" +
	"\vPullRequest\";\n" +
	"\tSyncError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05fatal\x18\x02 \x01(\bR\x05fatal\"\xbc\x01\n" +
	"\rServerMessage\x120\n" +
	"\tevent_ack\x18\x01 \x01(\v2\x11.cafi.v1.EventAckH\x00R\beventAck\x129\n" +
	"\fpull_request\x18\x02 \x01(\v2\x14.cafi.v1.PullRequestH\x00R\vpullRequest\x123\n" +
	"\n" +
	"sync_error\x18\x03 \x01(\v2\x12.cafi.v1.SyncErrorH\x00R\tsyncErrorB\t\n" +
	"\amessage*V\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_TYPE_UPSERT\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x022G\n" +
	"\aIndexer\x12<\n" +
	"\x04Sync\x12\x16.cafi.v1.ClientMessage\x1a\x16.cafi.v1.ServerMessage\"\x00(\x010\x01B>Z<github.com/VincentChalnot/cafi/internal/proto/cafi/v1;cafiv1b\x06proto3"

var (
	file_cafi_v1_cafi_proto_rawDescOnce sync.Once
	file_cafi_v1_cafi_proto_rawDescData []byte
)

func file_cafi_v1_cafi_proto_rawDescGZIP() []byte {
	file_cafi_v1_cafi_proto_rawDescOnce.Do(func() {
		file_cafi_v1_cafi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cafi_v1_cafi_proto_rawDesc), len(file_cafi_v1_cafi_proto_rawDesc)))
	})
	return file_cafi_v1_cafi_proto_rawDescData
}

var file_cafi_v1_cafi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cafi_v1_cafi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cafi_v1_cafi_proto_goTypes = []any{
	(EventType)(0),        // 0: cafi.v1.EventType
	(*Handshake)(nil),     // 1: cafi.v1.Handshake
	(*FileEvent)(nil),     // 2: cafi.v1.FileEvent
	(*ClientMessage)(nil), // 3: cafi.v1.ClientMessage
	(*EventAck)(nil),      // 4: cafi.v1.EventAck
	(*PullRequest)(nil),   // 5: cafi.v1.PullRequest
	(*SyncError)(nil),     // 6: cafi.v1.SyncError
	(*ServerMessage)(nil), // 7: cafi.v1.ServerMessage
}
var file_cafi_v1_cafi_proto_depIdxs = []int32{
	0, // 0: cafi.v1.FileEvent.event_type:type_name -> cafi.v1.EventType
	1, // 1: cafi.v1.ClientMessage.handshake:type_name -> cafi.v1.Handshake
	2, // 2: cafi.v1.ClientMessage.file_event:type_name -> cafi.v1.FileEvent
	4, // 3: cafi.v1.ServerMessage.event_ack:type_name -> cafi.v1.EventAck
	5, // 4: cafi.v1.ServerMessage.pull_request:type_name -> cafi.v1.PullRequest
	6, // 5: cafi.v1.ServerMessage.sync_error:type_name -> cafi.v1.SyncError
	3, // 6: cafi.v1.Indexer.Sync:input_type -> cafi.v1.ClientMessage
	7, // 7: cafi.v1.Indexer.Sync:output_type -> cafi.v1.ServerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cafi_v1_cafi_proto_init() }
func file_cafi_v1_cafi_proto_init() {
	if File_cafi_v1_cafi_proto != nil {
		return
	}
	file_cafi_v1_cafi_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientMessage_Handshake)(nil),
		(*ClientMessage_FileEvent)(nil),
	}
	file_cafi_v1_cafi_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_EventAck)(nil),
		(*ServerMessage_PullRequest)(nil),
		(*ServerMessage_SyncError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cafi_v1_cafi_proto_rawDesc), len(file_cafi_v1_cafi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cafi_v1_cafi_proto_goTypes,
		DependencyIndexes: file_cafi_v1_cafi_proto_depIdxs,
		EnumInfos:         file_cafi_v1_cafi_proto_enumTypes,
		MessageInfos:      file_cafi_v1_cafi_proto_msgTypes,
	}.Build()
	File_cafi_v1_cafi_proto = out.File
	file_cafi_v1_cafi_proto_goTypes = nil
	file_cafi_v1_cafi_proto_depIdxs = nil
}
